spring.application.name=LiteraturaA

spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=literalura_user
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
